### ISSUE TITLE
Uncaught Error: Uncaught, unspecified "error" event. (undefined)

### ISSUE THREAD

**Issue by CodeByTak** [learn-co/learn-ide-3#11]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 3.0.0
**Learn IDE Core**: 3.0.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 8.1 with Bing
**Thrown From**: [learn-ide-3](https://github.com/learn-co/learn-ide-3) package 3.0.0

### Stack Trace

Uncaught Error: Uncaught, unspecified "error" event. (undefined)

```
At events.js:165

Error: Uncaught, unspecified "error" event. (undefined)
    at EventEmitter.emit (events.js:163:17)
    at Terminal.emit (/app.asar/node_modules/learn-ide-3/lib/terminal.js:92:32)
    at /app.asar/node_modules/learn-ide-3/lib/terminal.js:80:16
    at Object.callback (/app.asar/node_modules/phoenix/priv/static/phoenix.js:470:16)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:615:21
    at Array.map (native)
    at Channel.trigger (/app.asar/node_modules/phoenix/priv/static/phoenix.js:614:10)
    at /app.asar/node_modules/phoenix/priv/static/phoenix.js:915:24
    at Array.forEach (native)
    at Socket.triggerChanError (/app.asar/node_modules/phoenix/priv/static/phoenix.js:914:21)
    at Socket.onConnClose (/app.asar/node_modules/phoenix/priv/static/phoenix.js:895:12)
    at WebSocket.conn.onclose (/app.asar/node_modules/phoenix/priv/static/phoenix.js:829:23)
```

### Commands

```
     -0:21.1.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -0:18.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
     -0:18.5.0 learn-ide:focus (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```

```

**Comment by CodeByTak** [comment]
somethings preventing me from opening labs specifically in the HTML and CCS section. Pls HELP
