### ISSUE TITLE
Failed to activate the learn-ide-3 package

### ISSUE THREAD

**Issue by dangeranger** [learn-co/learn-ide-3#7]
[Enter steps to reproduce:]

1. Install the learn-ide-3 package via Atom GUI
2. Click update and continue to install dependancies

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [learn-ide-3](https://github.com/learn-co/learn-ide-3) package 3.0.0

### Stack Trace

Failed to activate the learn-ide-3 package

```
At Cannot find module 'undefinedpackage.json'

Error: Cannot find module 'undefinedpackage.json'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/learn-ide-3/lib/application-metadata.js:3:16)
    at /packages/learn-ide-3/lib/application-metadata.js:3:85)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/learn-ide-3/lib/airbrake.js:8:50)
    at /packages/learn-ide-3/lib/airbrake.js:85:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/learn-ide-3/lib/learn-ide.js:6:43)
    at /packages/learn-ide-3/lib/learn-ide.js:245:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
atom-solo-dark-ui 1.3.0 
atom-ternjs 0.18.3 
busy-signal 1.4.3 
intentions 1.1.5 
learn-ide-3 3.0.0 
learn-ide-3-notifications 1.0.0 
learn-ide-3-tree 2.0.2 
learn-ide-material-ui 1.3.15 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
pure-syntax 0.3.0 
seti-ui 1.9.0 
vim-mode-plus 1.3.3 
```

**Comment by dangeranger** [comment]
Just a note, restarting Atom and disabling the `tree-view` package did not fix the issue.

**Comment by dangeranger** [comment]
As a work around I was able to use the functionality `leard-ide-3` package by disabling `learn-ide-3` without disabling any of its dependencies. Connecting to the remote virtual host works fine, the `learn-ide-3-tree` works as well.

**Comment by mtrussell** [comment]
I'm getting this error too. Tried disabling, restarting, re-enabling. It worked for that window, but when I opened a second window it threw the same error. Going to try uninstalling/reinstalling, but if that fails it looks like I'm just going to move to a local environment setup.

**Comment by mtrussell** [comment]
I'm getting this error too. Tried disabling, restarting, re-enabling. It worked for that window, but when I opened a second window it threw the same error. Going to try uninstalling/reinstalling, but if that fails it looks like I'm just going to move to a local environment setup.

**Comment by mtrussell** [comment]
I uninstalled and reinstalled several times, but it still throws the same error. I guess I will have to use a local environment.

**Comment by rometz** [comment]
Learn-Ide-3 was working fine yesterday, then I installed the rails gem on my computer and it has thrown everything off. Same errors as Dangeranger. Errors happen upon either: a) updating the learn-ide; or b) opening up a second window (usually through the command learn-open).

Windows 10x64
Atom: 1.7.8
Node: 10.4.0
npm: 6.1.0

**Comment by mtrussell** [comment]
I switched themes back to 'Atom Dark' UI and 'Atom Dark' Syntax and the error went away. I had activated a new theme yesterday. I guess that breaks everything...
